# Generated by Django 5.0 on 2024-10-22 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppSolicitudes', '0006_alter_solicitud_estado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
